[project]
name = "dg-portfolio-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Diego Gasch"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask (>=3.1.2,<4.0.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "flask-migrate (>=4.1.0,<5.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "marshmallow (>=4.2.1,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
